# Generated by Django 4.1.1 on 2022-10-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_alter_process_judicialclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='judicialClass',
        ),
        migrations.AddField(
            model_name='process',
            name='judicialClass',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='process.judicialclass'),
        ),
    ]
