# Generated by Django 4.1.2 on 2022-10-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_remove_process_judicialclass_process_judicialclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='judicialClass',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='judicialClass',
        ),
    ]
