# Generated by Django 4.1.2 on 2022-10-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_alter_process_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='process',
            name='judge',
            field=models.CharField(max_length=500, verbose_name='Judge'),
        ),
        migrations.AlterField(
            model_name='process',
            name='judicialClass',
            field=models.CharField(max_length=1000, verbose_name='Judicial Class'),
        ),
        migrations.AlterField(
            model_name='process',
            name='number',
            field=models.CharField(max_length=1000, verbose_name='Process Number'),
        ),
        migrations.AlterField(
            model_name='process',
            name='topic',
            field=models.CharField(max_length=1000, verbose_name='Process Topic'),
        ),
    ]
