# Generated by Django 4.1.2 on 2022-10-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_alter_process_category_alter_process_judge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='number',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Número do Processo:'),
        ),
        migrations.AlterField(
            model_name='process',
            name='parts',
            field=models.ManyToManyField(related_name='parts', to='process.parts', verbose_name='Partes:'),
        ),
    ]
