# Generated by Django 4.1.2 on 2022-10-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_alter_process_number_alter_process_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='number',
            field=models.CharField(max_length=1000, verbose_name='Número do Processo:'),
        ),
    ]
